[package]
name = "dtmf_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.1"
dtmf = {git = "https://gitlab.com/SnejUgal/dtfm"}
pv_recorder = "1.2.1"
dasp = "0.11.0"
